In [4]:
# importing libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
import seaborn as sns
from datetime import datetime, timedelta

import plotly.express as px
import plotly.graph_objects as go

plt.style.use("ggplot")

pd.set_option('display.max_columns', None)

In [5]:
# Reading the dataset
df = pd.read_csv("../data/Nassau Candy Distributor.csv")

df.head

<bound method NDFrame.head of        Row ID                      Order ID  Order Date   Ship Date  \
0           1  US-2021-103800-CHO-MIL-31000  03-01-2024  30-06-2026
1           2  US-2021-112326-CHO-TRI-54000  04-01-2024  01-07-2026
2           3  US-2021-112326-CHO-NUT-13000  04-01-2024  01-07-2026
3           4  US-2021-112326-CHO-SCR-58000  04-01-2024  01-07-2026
4           5  US-2021-141817-CHO-TRI-54000  05-01-2024  05-07-2026
...       ...                           ...         ...         ...
10189   10190  US-2024-143259-CHO-MIL-31000  30-12-2025  26-06-2030
10190   10191  US-2024-115427-CHO-NUT-13000  30-12-2025  26-06-2030
10191   10192  US-2024-156720-CHO-SCR-58000  30-12-2025  26-06-2030
10192   10193  US-2024-143259-CHO-TRI-54000  30-12-2025  26-06-2030
10193   10194  CA-2024-143500-CHO-SCR-58000  30-12-2025  26-06-2030

            Ship Mode  Customer ID Country/Region           City  \
0      Standard Class       103800  United States        Houston
1      Standard Class       112326  United States     Naperville
2      Standard Class       112326  United States     Naperville
3      Standard Class       112326  United States     Naperville
4      Standard Class       141817  United States   Philadelphia
...               ...          ...            ...            ...
10189  Standard Class       143259  United States  New York City
10190  Standard Class       115427  United States      Fairfield
10191  Standard Class       156720  United States       Loveland
10192  Standard Class       143259  United States  New York City
10193  Standard Class       143500         Canada  Charlottetown

             State/Province Postal Code   Division    Region     Product ID  \
0                     Texas       77095  Chocolate  Interior  CHO-MIL-31000
1                  Illinois       60540  Chocolate  Interior  CHO-TRI-54000
2                  Illinois       60540  Chocolate  Interior  CHO-NUT-13000
3                  Illinois       60540  Chocolate  Interior  CHO-SCR-58000
4              Pennsylvania       19143  Chocolate  Atlantic  CHO-TRI-54000
...                     ...         ...        ...       ...            ...
10189              New York       10009  Chocolate  Atlantic  CHO-MIL-31000
10190            California       94533  Chocolate   Pacific  CHO-NUT-13000
10191              Colorado       80538  Chocolate   Pacific  CHO-SCR-58000
10192              New York       10009  Chocolate  Atlantic  CHO-TRI-54000
10193  Prince Edward Island         C0A  Chocolate  Atlantic  CHO-SCR-58000

                            Product Name  Sales  Units  Gross Profit  Cost
0             Wonka Bar - Milk Chocolate   6.50      2          4.22  2.28
1      Wonka Bar - Triple Dazzle Caramel   7.50      2          4.90  2.60
2      Wonka Bar - Nutty Crunch Surprise  10.47      3          7.47  3.00
3         Wonka Bar -Scrumdiddlyumptious  10.80      3          7.50  3.30
4      Wonka Bar - Triple Dazzle Caramel  11.25      3          7.35  3.90
...                                  ...    ...    ...           ...   ...
10189         Wonka Bar - Milk Chocolate   9.75      3          6.33  3.42
10190  Wonka Bar - Nutty Crunch Surprise   6.98      2          4.98  2.00
10191     Wonka Bar -Scrumdiddlyumptious  10.80      3          7.50  3.30
10192  Wonka Bar - Triple Dazzle Caramel  26.25      7         17.15  9.10
10193     Wonka Bar -Scrumdiddlyumptious  10.80      3          7.50  3.30

[10194 rows x 18 columns]>

In [8]:
df.head().T

,0,1,2,3,4
Row ID,1,2,3,4,5
Order ID,US-2021-103800-CHO-MIL-31000,US-2021-112326-CHO-TRI-54000,US-2021-112326-CHO-NUT-13000,US-2021-112326-CHO-SCR-58000,US-2021-141817-CHO-TRI-54000
Order Date,03-01-2024,04-01-2024,04-01-2024,04-01-2024,05-01-2024
Ship Date,30-06-2026,01-07-2026,01-07-2026,01-07-2026,05-07-2026
Ship Mode,Standard Class,Standard Class,Standard Class,Standard Class,Standard Class
Customer ID,103800,112326,112326,112326,141817
Country/Region,United States,United States,United States,United States,United States
City,Houston,Naperville,Naperville,Naperville,Philadelphia
State/Province,Texas,Illinois,Illinois,Illinois,Pennsylvania
Postal Code,77095,60540,60540,60540,19143
Division,Chocolate,Chocolate,Chocolate,Chocolate,Chocolate
Region,Interior,Interior,Interior,Interior,Atlantic
Product ID,CHO-MIL-31000,CHO-TRI-54000,CHO-NUT-13000,CHO-SCR-58000,CHO-TRI-54000
Product Name,Wonka Bar - Milk Chocolate,Wonka Bar - Triple Dazzle Caramel,Wonka Bar - Nutty Crunch Surprise,Wonka Bar -Scrumdiddlyumptious,Wonka Bar - Triple Dazzle Caramel
Sales,6.5,7.5,10.47,10.8,11.25
Units,2,2,3,3,3
Gross Profit,4.22,4.9,7.47,7.5,7.35
Cost,2.28,2.6,3.0,3.3,3.9

In [9]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
10189,10190,US-2024-143259-CHO-MIL-31000,30-12-2025,26-06-2030,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42
10190,10191,US-2024-115427-CHO-NUT-13000,30-12-2025,26-06-2030,Standard Class,115427,United States,Fairfield,California,94533,Chocolate,Pacific,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,6.98,2,4.98,2.00
10191,10192,US-2024-156720-CHO-SCR-58000,30-12-2025,26-06-2030,Standard Class,156720,United States,Loveland,Colorado,80538,Chocolate,Pacific,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
10192,10193,US-2024-143259-CHO-TRI-54000,30-12-2025,26-06-2030,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,26.25,7,17.15,9.10
10193,10194,CA-2024-143500-CHO-SCR-58000,30-12-2025,26-06-2030,Standard Class,143500,Canada,Charlottetown,Prince Edward Island,C0A,Chocolate,Atlantic,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30

In [10]:
# Display the number of rows and columns in the dataframe
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.info()

Rows : 10194
Columns : 18
<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 2.9 MB

In [11]:
# Display summary statistics for all columns
df.describe(include='all')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
count,10194.000000,10194,10194,10194,10194,10194.000000,10194,10194,10194,10194,10194,10194,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
unique,NaN,8549,717,1338,4,NaN,2,542,59,654,3,4,15,15,NaN,NaN,NaN,NaN
top,NaN,US-2021-155502-CHO-MIL-31000,02-09-2025,07-06-2028,Standard Class,NaN,United States,New York City,California,10035,Chocolate,Pacific,CHO-MIL-31000,Wonka Bar - Milk Chocolate,NaN,NaN,NaN,NaN
freq,NaN,5,62,38,6120,NaN,9994,915,2001,263,9844,3253,2137,2137,NaN,NaN,NaN,NaN
mean,5097.500000,NaN,NaN,NaN,NaN,134468.961154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.908537,3.791838,9.166451,4.742087
std,2942.898656,NaN,NaN,NaN,NaN,20231.483007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.341020,2.228317,6.643740,5.061647
min,1.000000,NaN,NaN,NaN,NaN,100006.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,NaN,NaN,NaN,NaN,117212.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,NaN,NaN,NaN,NaN,133550.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,NaN,NaN,NaN,NaN,152051.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000000,5.000000,12.250000,5.700000
max,10194.000000,NaN,NaN,NaN,NaN,192314.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,260.000000,14.000000,130.000000,130.000000